# Generated by Django 4.2 on 2024-10-18 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='creator_id',
        ),
    ]
