# Generated by Django 4.2 on 2024-10-18 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_libro_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='creator_id',
        ),
    ]
