# Generated by Django 4.2 on 2024-10-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
    ]
