# Generated by Django 4.2 on 2024-10-18 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0002_novedad_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='creator_id',
        ),
    ]
