# Generated by Django 4.2 on 2024-10-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='link',
            field=models.URLField(max_length=250, verbose_name='Link formulario'),
        ),
    ]
