# Generated by Django 4.2 on 2024-10-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_examen_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='link',
            field=models.URLField(verbose_name='Link formulario'),
        ),
    ]
