# Generated by Django 4.2 on 2024-10-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alter_examen_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='division',
            name='creator_id',
        ),
    ]
