# Generated by Django 4.2 on 2024-10-18 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_remove_curso_creator_id_remove_division_creator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cde',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='creator_id',
        ),
    ]
